---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-operator-deployment
  labels:
    app.kubernetes.io/name: trino-operator
    app.kubernetes.io/instance: trino-operator
    app.kubernetes.io/version: "0.3.0-nightly"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: trino-operator
      app.kubernetes.io/instance: trino-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trino-operator
        app.kubernetes.io/instance: trino-operator
    spec:
      serviceAccountName: trino-operator-serviceaccount
      securityContext: {}
      containers:
        - name: trino-operator
          securityContext: {}
          image: "docker.stackable.tech/stackable/trino-operator:0.3.0-nightly"
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /etc/stackable/trino-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: trino-operator-configmap
