apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
spec:
  image:
    productVersion: "476"
    custom: oci.stackable.tech/sdp/trino:476-stackable0.0.0-dev-with-merger
    pullPolicy: Never
  clusterConfig:
    tls:
      serverSecretClass: short-tls
    catalogLabelSelector:
      matchLabels:
        trino: simple-trino
  coordinators:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: short-tls
spec:
  backend: 
    autoTls: 
      ca:
        secret:
          name: secret-provisioner-short-tls-ca
          namespace: stackable-operators
        autoGenerate: true
        caCertificateLifetime: 1m
