= Graceful shutdown

You can configure the graceful shutdown as described in xref:concepts:operations/pod_placement.adoc[].

== Coordinators

As a default, coordinators have `15` minutes to terminate gracefully.

== Workers
Trino supports https://trino.io/docs/current/admin/graceful-shutdown.html[graceful shutdown] of the workers.
This operator always adds a https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/[`PreStop` hook] to gracefully shut them down.
No additional configuration is needed, this guide is intended for users that need to tweak this mechanism.

The default graceful shutdown period is `1` hour, but it can be configured as follows:

[source,yaml]
----
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: trino
spec:
  # ...
  workers:
    config:
      gracefulShutdownTimeout: 1h
    roleGroups:
      default:
        replicas: 1
----

== Implementation
Once a worker Pod is asked to terminate, the `PreStop` hook is executed and the following timeline occurs:

1. The worker goes into `SHUTTING_DOWN` state.
2. The worker sleeps for `30` seconds to ensure that the coordinator has noticed the shutdown and stops scheduling new tasks on the worker.
3. The worker now waits till all tasks running on it complete. This will take as long as the longest running query takes.
4. The worker sleeps for `30` seconds to ensure that the coordinator has
noticed that all tasks are complete
5. The `PreStop` hook will never return, but the JVM will be shut down by the graceful shutdown mechanism.
6. When the graceful shutdown is not quick enough (e.g. a query runs longer than the graceful shutdown period), after `<graceful shutdown period> + 30s of step 2 + 30s of step 4 + 10s safety overhead` the Pod gets killed, regardless if it has shut down gracefully or not. This is achieved by setting `terminationGracePeriodSeconds` on the worker Pods. In this case queries running on the worker will fail.

WARNING: As of version 23.7, the secret-operator issues TLS certificates with a lifetime of 24h. It also adds an annotation to the Pod, so that it is restarted 30 minutes before the certificate expires (23.5h hours in this case). Currently, this results in all Pod using https (both coordinator and workers in a typical setup) restarting every 23.5 hours.
The TLS certificate lifetime can be configured once https://github.com/stackabletech/secret-operator/pull/306 is merged.

== Implications
All queries that take less than the minimal graceful shutdown period of all roleGroups (`1` hour as a default) are guaranteed to not be disturbed by regular termination of Pods.
They can obviously still fail when e.g. a Kubernetes node dies completely or the Pod does not get the time it takes to properly gracefully shut down.

Because of this the operator automatically restricts the execution time of queries to the minimal graceful shutdown period of all roleGroups using the Trino configuration `query.max-execution-time=3600s`.
This causes all queries that take longer than 1 hour to fail with the error message `Query failed: Query exceeded the maximum execution time limit of 3600s.00s`.

In case you need to execute queries that take longer than the configured graceful shutdown period, you need to increase the `query.max-execution-time` property as follows:

[source,yaml]
----
spec:
  coordinators:
    configOverrides:
      config.properties:
        query.max-execution-time: 24h
----

Please keep in mind, that queries taking longer than the graceful shutdown period are now subject to failure when a Trino worker gets shut down.
This can be circumvented by using https://trino.io/docs/current/admin/fault-tolerant-execution.html[Fault-tolerant execution], which is not supported natively yet.
Until properly supported, you have to use configOverrides to enable it.

== OPA requirements
In case you use OPA to authorize Trino requests, you need to make sure the user `admin` is authorized to trigger a graceful shutdown of the workers.
You can achieve this e.g. by adding the following rule, which grants `admin` the permissions to do anything - including graceful shutdown.

[source,rego]
----
allow {
  input.context.identity.user == "admin"
}
----

NOTE: We plan to add CustomResources, so that you can define your Trino ACLs via Kubernetes objects. In this case the trino-operator will generate the rego-rules for you, and will add the needed rules for graceful shutdown for you. Until then, you grant the permission yourself.
