= Installation
:description: Install the Stackable Operator for Trino using stackablectl or Helm. Includes optional setup for Hive, S3, and OPA integration.

On this page you install the Stackable operator for Trino as well as the commons, secret and listener operator which are required by all Stackable operators.

== Stackable operators

The xref:management:stackablectl:index.adoc[`stackablectl`] command line tool is the recommended way to interact with operators and dependencies.
If you have not installed `stackablectl`, follow the xref:management:stackablectl:installation.adoc[installation steps] to install it.
You can also use Helm instead.
OpenShift users may prefer installing the operator from the RedHat Certified Operator catalog using the OpenShift web console.

[tabs]
====
stackablectl::
+
--
Run the following command to install the Trino operator and its dependencies:

[source,console]
----
include::example$getting_started/code/getting_started.sh[tag=stackablectl-install-operators]
----

The tool prints

[source]
include::example$getting_started/code/install_output.txt[]

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`.
--

Helm::
+
--
NOTE: `helm repo` subcommands are not supported for OCI registries. The operators are installed directly, without adding the Helm Chart repository first.

Install the Stackable operators:

[source,console]
----
include::example$getting_started/code/getting_started.sh[tag=helm-install-operators]
----
--
====

== Optional installation steps

Some Trino connectors like `hive` or `iceberg` work together with the Apache Hive metastore and S3 buckets.
For these components extra steps are required.

* a Stackable Hive metastore
* an accessible S3 bucket
** an end-point, and access- and secret-keys
** data in the bucket (we use the https://archive.ics.uci.edu/ml/datasets/iris[Iris] dataset here)
* the following are optional
** a Stackable xref:secret-operator:index.adoc[Secret Operator] for certificates when deploying for TLS
** a Stackable xref:commons-operator:index.adoc[Commons Operator] for certificates when deploying for TLS authentication
** (for authorization): a Stackable xref:opa:index.adoc[OPA Operator]
** the https://repo.stackable.tech/#browse/browse:packages:trino-cli%2Ftrino-cli-477[Trino CLI] to test SQL queries

=== S3 bucket

Refer to the S3 provider.

=== Hive operator

Refer to the xref:hive:index.adoc[Hive operator] docs.
Both Hive and Trino need the same S3 authentication.

=== OPA operator

Refer to the xref:opa:index.adoc[OPA operator] docs.

== What's next

xref:getting_started/first_steps.adoc[Set up a Trino cluster] and its dependencies.
