---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-bundle-trino
  labels:
    opa.stackable.tech/bundle: "true"
data:
  trino.rego: |
    package trino

    import rego.v1

    default allow = false

    allow if {
      is_admin
    }

    is_admin() if {
      input.context.identity.user == "admin"
    }
