= Defining a Trino cluster

With the prerequisites fulfilled, the CRD for this operator can be created:
[source]
----
kubectl apply -f /etc/stackable/trino-operator/crd/trinocluster.crd.yaml
----

== Define an insecure cluster (testing)

Create an insecure single node Trino (v387) cluster for testing. You will access the UI/CLI via http with neither user/password credentials nor authorization. Please adapt the `s3` settings with your credentials (check `examples/simple-trino-cluster.yaml` for an example setting up Hive and Trino):

[source,yaml]
----
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  version: 387-stackable0.1.0
  catalogLabelSelector:
    matchLabels:
      trino: simple-trino
  coordinators:
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: hive
  labels:
    trino: simple-trino
spec:
  connector:
    hive:
      metastore:
        configMap: simple-hive-derby
      s3:
        inline:
          host: test-minio
          port: 9000
          accessStyle: Path
          credentials:
            secretClass: minio-credentials
----

To access the CLI please execute:
[source]
----
./trino-cli-387-executable.jar --debug --server http://<node>:<http-port> --user=admin
----

== Define a secure cluster (production)

There are multiple steps that must be taken to secure a Trino cluster:

1. Enable authentication
2. Enable TLS between the clients and coordinator
3. Enable internal TLS for communications between coordinators and workers

For testing purposes we use the https://trino.io/docs/current/installation/cli.html[Trino CLI].

=== Via authentication

If authentication is enabled, https://trino.io/docs/current/security/tls.html[TLS] for the coordinator as well as a shared secret for https://trino.io/docs/current/security/internal-communication.html[internal communications] (this is base64 and not encrypted) must be configured.

Securing the Trino cluster will disable all HTTP ports and disable the web interface on the HTTP port as well.

[source,yaml]
----
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  version: 387-stackable0.1.0
  config:
    tls:
      secretClass: trino-tls
  authentication:
    method:
      multiUser:
        userCredentialsSecret:
          name: simple-trino-users-secret
[..]
----

If no `config.tls.secretClass` is provided but authentication is enabled, it will default to `tls` provided by the xref:secret-operator::index.adoc[Secret Operator].

[source]
----
./trino-cli-387-executable.jar --debug --server https://<host>:<https-port> --user=admin  --keystore-path=keystore.p12 --keystore-password=changeit
----
or

[source]
----
./trino-cli-387-executable.jar --debug --server https://<host>:<https-port> --user=admin --insecure
----

=== Via TLS only

This will disable the HTTP port and UI access and encrypt client-server communications.

[source,yaml]
----
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  version: 387-stackable0.1.0
  config:
    tls:
      secretClass: trino-tls
[..]
----

[source]
----
./trino-cli-387-executable.jar --debug --server https://<host>:<https-port> --user=admin --keystore-path=keystore.p12 --keystore-password=changeit
----

=== Via internal TLS

Internal TLS is for encrypted and authenticated communications between coordinators and workers. Since this applies to all the data send and processed between the processes, this may reduce the performance significantly.

[source,yaml]
----
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  version: 387-stackable0.1.0
  config:
    internalTls:
      secretClass: trino-internal-tls
[..]
----

Since Trino has internal and external communications running over a single port, this will enable the HTTPS port but not expose it. Cluster access is only possible via HTTP.

[source]
----
./trino-cli-387-executable.jar --debug --server http://<host>:<http-port> --user=admin
----

== S3 connection specification

You can specify S3 connection details directly inside the `TrinoCatalog` specification
or by referring to an external `S3Connection` custom resource.

To specify S3 connection details directly as part of the `TrinoCatalog` resource, you
add an inline connection configuration as shown below:

[source,yaml]
----
s3: # <1>
  inline:
    host: test-minio # <2>
    port: 9000 # <3>
    pathStyleAccess: true # <4>
    secretClass: minio-credentials  # <5>
    tls:
      verification:
        server:
          caCert:
            secretClass: minio-tls-certificates #<6>
----
<1> Entry point for the connection configuration
<2> Connection host
<3> Optional connection port
<4> Optional flag if path-style URLs should be used; This defaults to `false`
    which means virtual hosted-style URLs are used.
<5> Name of the `Secret` object expected to contain the following keys:
    `accessKey` and `secretKey`
<6> Optional TLS settings for encrypted traffic. The `secretClass` can be provided by the Secret Operator or yourself.

A self provided S3 TLS secret can be specified like this:
[source,yaml]
----
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: minio-tls-certificates
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-tls-certificates
  labels:
    secrets.stackable.tech/class: minio-tls-certificates
data:
    ca.crt: <your-base64-encoded-ca>
    tls.crt: <your base64-encoded-public-key>
    tls.key: <your-base64-encoded-private-key>
----

It is also possible to configure the bucket connection details as a separate
Kubernetes resource and only refer to that object from the `TrinoCatalog` specification
like this:

[source,yaml]
----
s3:
  reference: my-connection-resource # <1>
----
<1> Name of the connection resource with connection details

The resource named `my-connection-resource` is then defined as shown below:

[source,yaml]
----
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: my-connection-resource
spec:
  host: test-minio
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: minio-credentials
----

This has the advantage that the connection configuration can be shared across
applications and reduces the cost of updating these details.





