= Security

== Authentication

Trino supports several https://trino.io/docs/current/security/authentication-types.html[authentication types].

=== Password

The Trino operator currently supports the following `PASSWORD` authenticators.

==== Password file

The https://trino.io/docs/current/security/password-file.html[file based authentication] can be defined as follows:

[source,yaml]
----
include::example$code/trino-file-authentication.yaml[]
----

The `simple-trino-users-secret` points to a manually created secret. This contains username and password pairs as shown in the previous snippet.

The username and password combinations are provided in the `stringData` field. The hashes are created using bcrypt with 10 rounds.

[source]
----
htpasswd -nbBC 10 admin admin
----

==== LDAP

The Trino operator supports https://trino.io/docs/current/security/ldap.html[LDAP authentication] as well. The following snippet shows how to configure `PASSWORD` authentication using LDAP:

[source,yaml]
----
include::example$code/trino-ldap-authentication.yaml[]
----

With this configuration, Trino will authenticate via `ldaps://openldap.default.svc.cluster.local:1636`.
The UI or Trino CLI need to authenticate with the user `integrationtest` and password `integrationtest`.

Please have a look at the LDAP https://github.com/stackabletech/trino-operator/tree/main/tests/templates/kuttl/ldap[integration tests] for testing, setting up OpenLDAP and creating the integrationtest user.

== Authorization

In order to authorize Trino via OPA, a `ConfigMap` containing Rego rules for Trino has to be applied. The following example is an all-access Rego rule for testing with the user `admin`. Do not use it in production!

[source,yaml]
----
include::example$code/opa-bundle-trino-cm.yaml[]
----

Users should write their own rego rules for more complex OPA authorization.