= Security

This page covers <<Authentication>> and <<Authorization>>.

== Authentication

Trino supports several https://trino.io/docs/current/security/authentication-types.html[authentication types].

=== Password

The Trino operator currently supports the following `PASSWORD` authenticators.

==== Password file

The https://trino.io/docs/current/security/password-file.html[file based authentication] can be defined as follows. First create a secret with your users:

[source,yaml]
----
include::example$code/trino-file-auth-snippet.yaml[tag=secret]
----

This contains username and password pairs as shown in the previous snippet. The username and password combinations are provided in the `stringData` field. The hashes are created using bcrypt with 10 rounds:

[source]
----
htpasswd -nbBC 10 admin admin
----

Then reference the secret in your TrinoCluster definition:

[source,yaml]
----
include::example$code/trino-file-auth-snippet.yaml[tag=trino]
----

=== LDAP

The Trino operator supports https://trino.io/docs/current/security/ldap.html[LDAP authentication] as well and authentication in Stackable is done using xref:home:concepts:authentication.adoc#authenticationclass[AuthenticationClasses]:

[source,yaml]
----
include::example$code/trino-ldap-auth-snippet.yaml[tag=authclass]
----

NOTE: You can follow the xref:home:tutorials:authentication_with_openldap.adoc[] tutorial to learn how to create an AuthenticationClass for an LDAP server.

With an AuthenticationClass ready, `PASSWORD` authentication using LDAP is done by referincing the LDAP AuthenticationClass: 

[source,yaml]
----
include::example$code/trino-ldap-auth-snippet.yaml[tag=trino]
----

In the Trino CLI and web interface, LDAP users can now be used to log in.

== Authorization

In order to authorize Trino via OPA, a `ConfigMap` containing Rego rules for Trino has to be applied. The following example is an all-access Rego rule for testing with the user `admin`. Do not use it in production!

[source,yaml]
----
include::example$code/opa-bundle-trino-cm.yaml[]
----

Users should write their own rego rules for more complex OPA authorization.