= Environment variables

This operator accepts the following environment variables:

== KUBERNETES_CLUSTER_DOMAIN

*Default value*: cluster.local

*Required*: false

*Multiple values*: false

This instructs the operator, which value it should use for the Kubernetes `clusterDomain` setting.
Make sure to keep this in sync with whatever setting your cluster uses.
Please see the documentation xref:guides:kubernetes-cluster-domain.adoc[on configuring the Kubernetes cluster domain] for more information on this feature.

[source]
----
export KUBERNETES_CLUSTER_DOMAIN=mycluster.local
cargo run -- run
----

or via docker:

[source]
----
docker run \
--name trino-operator \
--network host \
--env KUBECONFIG=/home/stackable/.kube/config \
--env KUBERNETES_CLUSTER_DOMAIN=mycluster.local \
--mount type=bind,source="$HOME/.kube/config",target="/home/stackable/.kube/config" \
docker.stackable.tech/stackable/trino-operator:latest
----

== PRODUCT_CONFIG

*Default value*: `/etc/stackable/trino-operator/config-spec/properties.yaml`

*Required*: false

*Multiple values*: false

[source]
----
export PRODUCT_CONFIG=/foo/bar/properties.yaml
cargo run -- run
----

or via docker:

----
docker run \
    --name trino-operator \
    --network host \
    --env KUBECONFIG=/home/stackable/.kube/config \
    --env PRODUCT_CONFIG=/my/product/config.yaml \
    --mount type=bind,source="$HOME/.kube/config",target="/home/stackable/.kube/config" \
    docker.stackable.tech/stackable/trino-operator:latest
----

== WATCH_NAMESPACE

*Default value*: All namespaces

*Required*: false

*Multiple values*: false

The operator **only** watches for resources in the provided namespace `test`:

[source]
----
export WATCH_NAMESPACE=test
cargo run -- run
----

or via docker:

[source]
----
docker run \
--name trino-operator \
--network host \
--env KUBECONFIG=/home/stackable/.kube/config \
--env WATCH_NAMESPACE=test \
--mount type=bind,source="$HOME/.kube/config",target="/home/stackable/.kube/config" \
docker.stackable.tech/stackable/trino-operator:latest
----
