= Concepts

== Connectors

https://trino.io/docs/current/overview/use-cases.html#what-trino-is[Trino] is a tool designed to efficiently query vast amounts of data using distributed queries. It is not a database with its own store but rather interacts with many types of store. Trino connects to these stores - or data sources - via https://trino.io/docs/current/connector.html[connectors].
Each connector enables access to a specific underlying datasource such as a Hive warehouse, a PostgreSQL database or a Druid instance.

A Trino cluster comprises two roles: the Coordinator, responsible for managing and monitoring work loads, and the Worker, which is responsible for executing specific tasks that together make up a work load. The workers fetch data from the connectors, execute tasks and share intermediate results. The coordinator collects and consolidates these results for the end-user.

== Catalogs

An instance of a connector is called a catalog.
Think of a setup containing a large Hive warehouse running on HDFS.
There may exist two different catalogs called e.g. `warehouse_1` and `warehouse_2` each specifying the same `hive` connector.

Currently, the following connectors are supported:

* https://trino.io/docs/current/connector/hive.html[Hive]
* https://trino.io/docs/current/connector/iceberg.html[Iceberg]

== Catalog references

Within the Stackable a `TrinoCatalog` consists of the following:

- a mandatory reference to a Hive metastore configuration map (in the same namespace)
- optional references to S3 and/or HDFS storage

A catalog should be re-usable within multiple Trino clusters. Catalogs are referenced by Trino clusters with labels and label selectors: this is consistent with the Kubernetes paradigm and keeps the definitions simple and flexible. An example of this is shown here: xref:usage_guide:catalogs.adoc[].