---
apiVersion: v1
data:
{{ (.Files.Glob "configs/*").AsConfig | indent 2 }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
  {{- include "operator.labels" . | nindent 4 }}
