apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple
spec:
  version: "0.0.362"
  nodeEnvironment: production
  hiveReference:
    namespace: default
    name: simple-derby
  coordinators:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - main-1.stackable.demo
        config:
          coordinator: true
          nodeDataDir: /tmp/trino/data
          metricsPort: 10200
          httpServerHttpPort: 8080
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          s3Connection:
            endPoint: s3-de-central.profitbricks.com
            accessKey: 00c6d2f2d6c0a460aab7
            secretKey: d2WzGCD4zSYNOwAK9leXMtWP0/KcZpCbLjTg8zwf
            sslEnabled: false
            pathStyleAccess: true
  workers:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - worker-1.stackable.demo
                - worker-2.stackable.demo
                - worker-3.stackable.demo
        replicas: 1
        config:
          nodeDataDir: /tmp/trino/data2
          metricsPort: 10201
          httpServerHttpPort: 8081
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          s3Connection:
            endPoint: s3-de-central.profitbricks.com
            accessKey: 00c6d2f2d6c0a460aab7
            secretKey: d2WzGCD4zSYNOwAK9leXMtWP0/KcZpCbLjTg8zwf
            sslEnabled: false
            pathStyleAccess: true
