apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  version: "0.0.362"
  nodeEnvironment: production
  hive:
    namespace: default
    name: simple-hive-derby
  opa:
    namespace: default
    name: simple-opa
  authentication:
    method:
      multiUser:
        userCredentialsSecret:
          namespace: default
          name: simple-trino-users-secret
  authorization:
    package: trino
    permissions:
      admin:
        schemas:
          read: true
          write: true
        tables:
          iris_parquet:
            read: true
            write: true
          iris_csv:
            read: true
            write: true
      bob:
        schemas:
          read: false
          write: false
        tables:
          iris_parquet:
            read: true
  s3:
    endPoint: changeme
    accessKey: changeme
    secretKey: changeme
    sslEnabled: false
    pathStyleAccess: true
  coordinators:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config: {}
  workers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config: {}
