---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  image:
    productVersion: "396"
    stackableVersion: 0.3.0
  catalogLabelSelector:
    matchLabels:
      trino: simple-trino
  coordinators:
    roleGroups:
      default:
        replicas: 1
        selector:
          matchLabels:
            nodeType: druid-data
  workers:
    roleGroups:
      default:
        replicas: 1
        selector:
          matchLabels:
            nodeType: druid-data
