---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trino-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - get
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - stackable-products-scc
    verbs:
      - use
