---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: trino-operator.v23.4.0
spec:
  annotations:
    support: stackable.tech
    olm.properties: '[]'
    categories: Storage
    capabilities: Full Lifecycle
    description: Stackable Operator for Trino
    repository: https://github.com/stackabletech/trino-operator
    containerImage: docker.stackable.tech/stackable/trino-operator:23.4.0

  displayName: Stackable Operator for Trino
  description: |-
    This is a Kubernetes operator to manage [Trino](https://trino.io/) ensembles. The Stackable Trino Operator
    is part of the Stackable Data Platform, a curated selection of the best open source data apps like Kafka, Druid, Trino or Spark, all
    working together seamlessly. Based on Kubernetes, it runs everywhere – on prem or in the cloud.

    You can install the operator using [stackablectl or helm](https://docs.stackable.tech/trino/stable/getting_started/installation.html).
    See it in action in one of our [demos](https://stackable.tech/en/demos/) or follow this
    [tutorial](https://docs.stackable.tech/trino/stable/getting_started/first_steps.html).

    N.B. this operator requires the following Stackable internal operators to be installed as well:

    - [Commons Operator](https://github.com/stackabletech/commons-operator)
    - [Secret Operator](https://github.com/stackabletech/secret-operator)
    - [Druid Operator](https://github.com/stackabletech/druid-operator)
  keywords:
    - trino
  maintainers:
    - email: info@stackable.tech
      name: Stackable GmbH
  maturity: stable
  provider:
    name: Stackable GmbH
    url: https://stackable.tech
  version: 23.4.0
  minKubeVersion: 1.23.0

  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces

  customresourcedefinitions:
    owned:
      # a list of CRDs that this operator owns
      # name is the metadata.name of the CRD (which is of the form <plural>.<group>)
      - name: trinoclusters.trino.stackable.tech
        # version is the spec.versions[].name value defined in the CRD
        version: v1alpha1
        # kind is the CamelCased singular value defined in spec.names.kind of the CRD.
        kind: TrinoCluster
        # human-friendly display name of the CRD for rendering in graphical consoles (optional)
        displayName: Trino Cluster
        # a short description of the CRDs purpose for rendering in graphical consoles (optional)
        description: Represents a Trino Cluster
      - name: trinocatalogs.trino.stackable.tech
        version: v1alpha1
        kind: TrinoCatalog
        displayName: Trino Catalog
        description: Represents a Trino Catalog

  relatedImages:
    - name: trino-operator
      image: docker.stackable.tech/stackable/trino-operator:23.4.0
  install:
    # strategy indicates what type of deployment artifacts are used
    strategy: deployment
    # spec for the deployment strategy is a list of deployment specs and required permissions - similar to a pod template used in a deployment
    spec:
      permissions:
        - serviceAccountName: trino-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - '*'
      # permissions required at the cluster scope
      clusterPermissions:
        - serviceAccountName: trino-operator
          rules:
            - apiGroups:
                - opa.stackable.tech
              resources:
                - regorules
              verbs:
                - create
                - get
                - list
                - watch
                - patch
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
                - configmaps
                - secrets
                - services
                - endpoints
                - serviceaccounts
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - get
                - create
                - delete
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
            - apiGroups:
                - events.k8s.io
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - trino.stackable.tech
              resources:
                - trinoclusters
              verbs:
                - get
                - list
                - patch
                - watch
            - apiGroups:
                - trino.stackable.tech
              resources:
                - trinoclusters/status
              verbs:
                - patch
            - apiGroups:
                - s3.stackable.tech
              resources:
                - s3connections
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - trino.stackable.tech
              resources:
                - trinocatalogs
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - authentication.stackable.tech
              resources:
                - authenticationclasses
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
              resourceNames:
                - trino-clusterrole
              verbs:
                - bind
            - apiGroups:
                - security.openshift.io
              resources:
                - securitycontextconstraints
              resourceNames:
                - hostmount-anyuid
              verbs:
                - use

      deployments:
        - name: trino-operator
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                app.kubernetes.io/name: trino-operator
                app.kubernetes.io/instance: trino-operator
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: trino-operator
                  app.kubernetes.io/instance: trino-operator
              spec:
                serviceAccountName: trino-operator
                securityContext: {}
                containers:
                  - name: trino-operator
                    securityContext: {}
                    image: docker.stackable.tech/stackable/trino-operator:23.4.0
                    imagePullPolicy: IfNotPresent
                    resources: {}
                    volumeMounts:
                      - mountPath: /etc/stackable/trino-operator/config-spec
                        name: config-spec
                volumes:
                  - name: config-spec
                    configMap:
                      name: trino-operator-configmap
