# yamllint disable-file
---
# tag::authentication_class[]
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-trino-file-auth
spec:
  provider:
    static:
      userCredentialsSecret:
        name: simple-trino-users-secret
# end::authentication_class[]
---
# tag::secret[]
apiVersion: v1
kind: Secret
metadata:
  name: simple-trino-users-secret
type: kubernetes.io/opaque
stringData:
  admin: admin
  alice: alice
  bob: alice
# end::secret[]
---
# tag::trino[]
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
spec:
  clusterConfig:
    authentication:
      - authenticationClass: simple-trino-file-auth
# end::trino[]
